delight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
    path('reservations/', include('reservations.urls')),
    path('', include('menu.urls')),
    path('', include('staff.urls')),
]

main/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

menu/urls.py
from django.urls import path
from .views import menu, add_menu_item, manage_menu_items, delete_menu_item, edit_menu_item

urlpatterns = [
    path('menu/', menu, name='menu'),
    path('menu/add_menu_item/', add_menu_item, name='add_menu_item'),
    path('menu/manage_menu_items/', manage_menu_items, name='manage_menu_items'),
    path('menu/delete/<int:pk>/', delete_menu_item, name='delete_menu_item'),
    path('menu/edit/<int:pk>/', edit_menu_item, name='edit_menu_item'),
]

menu/models.py
from django.db import models
from cloudinary.models import CloudinaryField
import cloudinary

class MenuItem(models.Model):
    """
    Model representing an item on the menu.

    Attributes:
    ----------
    CATEGORY_CHOICES : list
        List of tuples representing the categories an item can belong to.
    name : str
        Name of the menu item.
    description : str
        Description of the menu item.
    price : decimal
        Price of the menu item, with a maximum of 5 digits and 2 decimal places.
    category : str
        Category of the menu item, chosen from CATEGORY_CHOICES.
    image : CloudinaryField
        Image of the menu item, stored using Cloudinary.

    Methods:
    -------
    __str__():
        Returns the name of the menu item.
    """

    CATEGORY_CHOICES = [
        ('starter', 'Starter'),
        ('main', 'Main'),
        ('dessert', 'Dessert'),
    ]

    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
    image = CloudinaryField('image')

    def __str__(self):
        return self.name

menu/forms.py
from django import forms
from .models import MenuItem

class MenuItemForm(forms.ModelForm):
    """
    Form for creating and updating menu items.

    This form is based on the MenuItem model and includes fields for
    'name', 'description', 'price', 'category', and 'image'.

    Attributes:
    - model: MenuItem
    - fields: ['name', 'description', 'price', 'category', 'image']
    
    """
    class Meta:
        model = MenuItem
        fields = ['name', 'description', 'price', 'category', 'image']

menu/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import MenuItem
from .forms import MenuItemForm
from itertools import chain
from django.contrib import messages
import cloudinary.uploader
import cloudinary.api
from cloudinary import CloudinaryImage

def menu(request):
    """
    Display the menu with all categories: starters, mains, and desserts.
    """
    starters = MenuItem.objects.filter(category='starter')
    mains = MenuItem.objects.filter(category='main')
    desserts = MenuItem.objects.filter(category='dessert')

    combined_menu = list(chain(starters, mains, desserts))

    return render(request, 'menu.html', {
        'starters': starters,
        'mains': mains,
        'desserts': desserts,
        'combined_menu': combined_menu,
    })


def add_menu_item(request):
    """
    Handle the addition of a new menu item.
    """
    if request.method == 'POST':
        form = MenuItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Menu item successfully added')
            return redirect('manage_menu_items')
    else:
        form = MenuItemForm()
    return render(request, 'add_menu_item.html', {'form': form})


def manage_menu_items(request):
    """
    Display all menu items for management.
    """
    menu_items = MenuItem.objects.all()
    return render(request, 'manage_menu_items.html', {'menu_items': menu_items})


def edit_menu_item(request, pk):
    """
    Handle the editing of an existing menu item.
    """
    menu_item = get_object_or_404(MenuItem, pk=pk)
    if request.method == 'POST':
        form = MenuItemForm(request.POST, request.FILES, instance=menu_item)
        if form.is_valid():
            form.save()
            messages.success(request, 'Menu item successfully edited')
            return redirect('manage_menu_items')
    else:
        form = MenuItemForm(instance=menu_item)
    return render(request, 'edit_menu_item.html', {'form': form})


def delete_menu_item(request, pk):
    """
    Handle the deletion of a menu item.
    """
    item = get_object_or_404(MenuItem, pk=pk)
    if request.method == 'POST':
        item.delete()
        messages.success(request, 'Menu item successfully deleted')
        return redirect('manage_menu_items')
    return render(request, 'delete_menu_item.html', {'item': item})

menu/templates/add_menu_item.html
{% extends "base.html" %}
{% block title %}Add Menu Item{% endblock title %}

{% block content %}
<div class="container my-5">
    <h2>Add Menu Item</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary" type="button" onclick="window.history.back();">Cancel</button>
        <button type="submit" class="btn bg-navy">Add Item</button>
    </form>
</div>
{% endblock %}

menu/templates/delete_menu_item.html
{% extends "base.html" %}
{% block title %}Delete Menu Item{% endblock title %}

{% block content %}
<div class="container my-5">
    <h2>Delete Menu Item</h2>
    <p>Are you sure you want to delete {{ item.name }}?</p>
    <form method="POST">
        {% csrf_token %}
        <button class="btn btn-secondary" type="button" onclick="window.history.back();">Cancel</button>
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>
{% endblock %}

menu/templates/edit_menu_item.html
{% extends "base.html" %}
{% block title %}Edit Menu Item{% endblock title %}

{% block content %}
<div class="container mt-4 mb-4">
    <h2>Edit Menu Item</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name:</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="id_description">Description:</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_price">Price:</label>
            {{ form.price }}
        </div>
        <div class="form-group">
            <label for="id_category">Category:</label>
            {{ form.category }}
        </div>
        <div class="form-group">
            <label for="id_image">Image:</label>
            {{ form.image }}
        </div>
        <a href="{% url 'manage_menu_items' %}" class="btn btn-secondary">Cancel</a>
        <button type="submit" class="btn bg-navy">Save Changes</button>
    </form>
</div>
{% endblock content %}

menu/templates/manage_menu_items.html
{% extends "base.html" %}
{% block title %}Manage Menu Items{% endblock %}

{% block content %}
<div class="container">
    <h2>Manage Menu Items</h2>
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Category</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for menu_item in menu_items %}
            <tr>
                <td>{{ menu_item.name }}</td>
                <td>{{ menu_item.description }}</td>
                <td>{{ menu_item.category }}</td>
                <td>{{ menu_item.price }}</td>
                <td>
                    <a href="{% url 'edit_menu_item' menu_item.id %}" class="btn bg-navy">Edit</a>
                    <a href="{% url 'delete_menu_item' menu_item.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'staff_dashboard' %}" class="btn btn-secondary">Cancel</a>
</div>
{% endblock %}

menu/templates/menu.html
{% extends "base.html" %}

{% block title %}Menu{% endblock title %}

{% block content %}
<section class="container my-5">
    <div class="text-center">
        <h1 class="bg-dark text-gold display-2 menu-title">Menu</h1>
        <p class="display-5 lead text-large">Discover our delicious selection of dishes carefully crafted to tantalize your taste buds.</p>
        <p class="text-muted font-italic">Click on a menu item name to view full details and an image of the dish.</p>
    </div>

    <!-- Starters Section -->
    <section class="menu-section">
        <h2 class="bg-dark text-gold text-center menu-category-heading">Starters</h2>
        <div class="list-group">
            {% for starter in starters %}
                <div class="list-group-item-action" data-toggle="modal" data-target="#starterModal{{ starter.id }}">
                    <span class="mb-4 d-inline-block" style="cursor: pointer;" onmouseover="this.style.textDecoration='underline';" onmouseout="this.style.textDecoration='none'; this.style.color='';">
                        {{ starter.name }}
                    </span>
                    <span class="float-right">${{ starter.price }}</span>
                </div>
            {% endfor %}
        </div>
    </section>

    <!-- Mains Section -->
    <section class="menu-section">
        <h2 class="bg-dark text-gold text-center menu-category-heading">Mains</h2>
        <div class="list-group">
            {% for main in mains %}
                <div class="list-group-item-action" data-toggle="modal" data-target="#mainModal{{ main.id }}">
                    <span class="mb-4 d-inline-block" style="cursor: pointer;" onmouseover="this.style.textDecoration='underline';" onmouseout="this.style.textDecoration='none'; this.style.color='';">
                        {{ main.name }}
                    </span>
                    <span class="float-right">${{ main.price }}</span>
                </div>
            {% endfor %}
        </div>
    </section>

    <!-- Desserts Section -->
    <section class="menu-section">
        <h2 class="bg-dark text-gold text-center menu-category-heading">Desserts</h2>
        <div class="list-group">
            {% for dessert in desserts %}
                <div class="list-group-item-action" data-toggle="modal" data-target="#dessertModal{{ dessert.id }}">
                    <span class="mb-4 d-inline-block" style="cursor: pointer;" onmouseover="this.style.textDecoration='underline';" onmouseout="this.style.textDecoration='none'; this.style.color='';">
                        {{ dessert.name }}
                    </span>
                    <span class="float-right">${{ dessert.price }}</span>
                </div>
            {% endfor %}
        </div>
    </section>
</section>

<!-- Modals -->
{% for item in combined_menu %}
<div class="modal fade" id="{{ item.category }}Modal{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="{{ item.category }}Modal{{ item.id }}Label" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="{{ item.category }}Modal{{ item.id }}Label">{{ item.name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <img src="{{ item.image.url }}" class="img-fluid mx-auto d-block" alt="{{ item.name }} Image">
            </div>
            <div class="modal-footer">
                <div class="w-100 text-left">
                    <p class="m-0">{{ item.description }}</p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endfor %}
{% endblock content %}